name: C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_DIR: build
  BUILD_TYPE: Release # single source of truth

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DCMAKE_CXX_STANDARD=20

      - name: Build
        # --config is harmless on single-config generators, required on MSVC/Xcode
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        run: |
          cd ${{ env.BUILD_DIR }}
          ctest --output-on-failure -C ${{ env.BUILD_TYPE }}
