name: C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
    env:
      CMAKE_BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false # avoid CRLF issues on Windows

      - name: Disable CRLF conversion (Windows)
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload CTest results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-log-${{ runner.os }}
          path: build/Testing/Temporary/LastTest.log
